Release v0.0.65_2025-05-13_12:25:31_UTC

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -127,24 +127,20 @@ jobs:
         shell: pwsh
         run: |
           choco install msys2
-          refreshenv
-          C:\tools\msys64\usr\bin\bash -lc "pacman -Syu --noconfirm"
-          C:\tools\msys64\usr\bin\bash -lc "pacman -S --noconfirm base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-gcc mingw-w64-x86_64-binutils mingw-w64-x86_64-headers git mingw-w64-x86_64-cmake mingw-w64-x86_64-imagemagick"
+          C:\tools\msys64\usr\bin\bash.exe -lc "pacman -Syu --noconfirm"
+          C:\tools\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-gcc mingw-w64-x86_64-binutils mingw-w64-x86_64-headers git mingw-w64-x86_64-cmake mingw-w64-x86_64-imagemagick"
           echo "C:\tools\msys64\mingw64\bin;$env:PATH" | Out-File -Encoding ASCII -Append $env:GITHUB_PATH
 
       - name: Build for Windows
         if: runner.os == 'Windows'
         shell: bash
         run: |
-          ln -sf /c/tools/msys64/mingw64/bin/cpp.exe /c/tools/msys64/mingw64/bin/x86_64-w64-mingw32-cpp.exe
           echo "MESA_PATH=${{ github.workspace }}/mesa" >> $GITHUB_ENV
           echo "PATH=${MESA_PATH};$PATH" >> $GITHUB_ENV
-          echo "INCLUDE=C:\tools\msys64\mingw64\x86_64-w64-mingw32\include" >> $GITHUB_ENV
-          echo "MESA_PATH from GITHUB_ENV: $MESA_PATH"
-          echo "PATH from GITHUB_ENV: $PATH"
-          echo "INCLUDE from GITHUB_ENV: $INCLUDE"
           cd ./examples
           chmod a+x ./build_example.sh
+          file favicon.ico || echo "Failed to check favicon.ico format"
+          ls -l favicon.ico || echo "favicon.ico not found"
           ./build_example.sh
           ./build_example.sh test
 
